export const polizas = [
  {
    linea_negocio: "Autos",
    oficina_emision: "Sucursal 1, León, Guanajuato",
    id_oficina_emision: "0004",
    numero_poliza: "34505",
    nombre_contratante_asegurado: "Jorge Murillo",
    nombre_beneficiario: "Jorge Murillo",
    estado_vigencia_id: "1",
    estado_pago_id: "1",
    fecha_inicio_vigencia: "09/06/2023",
    fecha_fin_vigencia: "09/06/2024",
    fecha_emision: "10/06/2023",
    periodicidad_pago: "Mensual",
    info_vehiculo: {
      tipo: "Aveo",
      marca: "Chevrolet",
      modelo: "2023",
      color: "Rojo",
      placas: "GVE-502-B",
    },
    siniestros: [],
  },
  {
    linea_negocio: "Autos",
    oficina_emision: "Sucursal 1, Ciudad de México",
    id_oficina_emision: "0001",
    numero_poliza: "12345",
    nombre_contratante_asegurado: "María Pérez",
    nombre_beneficiario: "María Pérez",
    estado_vigencia_id: "1",
    estado_pago_id: "0",
    fecha_inicio_vigencia: "10/08/2023",
    fecha_fin_vigencia: "10/08/2024",
    fecha_emision: "11/08/2023",
    periodicidad_pago: "Anual",
    info_vehiculo: {
      tipo: "Corolla",
      marca: "Toyota",
      modelo: "2022",
      color: "Azul",
      placas: "XYZ-789",
    },
    siniestros: [
      {
        fecha_ocurrencia: "12/06/2023",
        hora_ocurrencia: "16:30",
        lugar_ocurrencia: "blvd La Luz esq. blvd José María Morelos, León Gto",
        nombre_reportador: "María Pérez",
        telefono_reportador: "4777861996",
        email_reportador: "maria.perez@gmail.com",
        descripcion_siniestro: "Choque en cruce peatonal por esquivar transeunte contra poste de luz",
        placas: "XYZ-789",
        color: "Azul",
        observaciones: "Conductor no traia lentes, licencia menciona que ocupa",
        fecha_registro_ocurrencia: "13/06/2023", 
        numero_siniestro: "1",
        nombre_ajustador: "Juan Camarillo",
      },
    ],
  },
  {
    linea_negocio: "Daños",
    oficina_emision: "Sucursal 2, Guadalajara, Jalisco",
    id_oficina_emision: "0003",
    numero_poliza: "67890",
    nombre_contratante_asegurado: "Ana López",
    nombre_beneficiario: "Ana López",
    estado_vigencia_id: "1",
    estado_pago_id: "1",
    fecha_inicio_vigencia: "05/09/2023",
    fecha_fin_vigencia: "05/09/2024",
    fecha_emision: "06/09/2023",
    periodicidad_pago: "Mensual",
    info_vehiculo: {
      tipo: "N/A",
      marca: "N/A",
      modelo: "N/A",
      color: "N/A",
      placas: "N/A",
    },
    siniestros: [],
  },
  {
    linea_negocio: "Autos",
    oficina_emision: "Sucursal 1, Puebla, Puebla",
    id_oficina_emision: "0005",
    numero_poliza: "24680",
    nombre_contratante_asegurado: "Luis González",
    nombre_beneficiario: "Luis González",
    estado_vigencia_id: "0",
    estado_pago_id: "0",
    fecha_inicio_vigencia: "12/07/2022",
    fecha_fin_vigencia: "12/07/2023",
    fecha_emision: "13/07/2022",
    periodicidad_pago: "Semestral",
    info_vehiculo: {
      tipo: "Civic",
      marca: "Honda",
      modelo: "2023",
      color: "Gris",
      placas: "ABC-123-C",
    },
    siniestros: [],
  },
  {
    linea_negocio: "AP",
    oficina_emision: "Sucursal 1, Monterrey, Nuevo León",
    id_oficina_emision: "0006",
    numero_poliza: "13579",
    nombre_contratante_asegurado: "Marta Ramírez",
    nombre_beneficiario: "Marta Ramírez",
    estado_vigencia_id: "1",
    estado_pago_id: "1",
    fecha_inicio_vigencia: "20/01/2023",
    fecha_fin_vigencia: "20/01/2024",
    fecha_emision: "21/01/2023",
    periodicidad_pago: "Anual",
    info_vehiculo: {
      tipo: "N/A",
      marca: "N/A",
      modelo: "N/A",
      color: "N/A",
      placas: "N/A",
    },
    siniestros: [],
  },
  {
    linea_negocio: "Daños",
    oficina_emision: "Sucursal 1, Querétaro, Querétaro",
    id_oficina_emision: "0007",
    numero_poliza: "98765",
    nombre_contratante_asegurado: "Carlos Rodríguez",
    nombre_beneficiario: "Carlos Rodríguez",
    estado_vigencia_id: "1",
    estado_pago_id: "1",
    fecha_inicio_vigencia: "03/04/2023",
    fecha_fin_vigencia: "03/04/2024",
    fecha_emision: "04/04/2023",
    periodicidad_pago: "Mensual",
    info_vehiculo: {
      tipo: "N/A",
      marca: "N/A",
      modelo: "N/A",
      color: "N/A",
      placas: "N/A",
    },
    siniestros: [],
  },
  {
    linea_negocio: "Autos",
    oficina_emision: "Sucursal 1, Tijuana, Baja California",
    id_oficina_emision: "0008",
    numero_poliza: "54321",
    nombre_contratante_asegurado: "Laura García",
    nombre_beneficiario: "Laura García",
    estado_vigencia_id: "1",
    estado_pago_id: "0",
    fecha_inicio_vigencia: "15/02/2023",
    fecha_fin_vigencia: "15/02/2024",
    fecha_emision: "16/02/2023",
    periodicidad_pago: "Mensual",
    info_vehiculo: {
      tipo: "Sentra",
      marca: "Nissan",
      modelo: "2022",
      color: "Plata",
      placas: "DEF-456-E",
    },
    siniestros: [],
  },
  {
    linea_negocio: "AP",
    oficina_emision: "Sucursal 1, Veracruz, Veracruz",
    id_oficina_emision: "0009",
    numero_poliza: "112233",
    nombre_contratante_asegurado: "Ricardo Méndez",
    nombre_beneficiario: "Ricardo Méndez",
    estado_vigencia_id: "1",
    estado_pago_id: "1",
    fecha_inicio_vigencia: "08/05/2023",
    fecha_fin_vigencia: "08/05/2024",
    fecha_emision: "09/05/2023",
    periodicidad_pago: "Anual",
    info_vehiculo: {
      tipo: "N/A",
      marca: "N/A",
      modelo: "N/A",
      color: "N/A",
      placas: "N/A",
    },
    siniestros: [],
  },
  {
    linea_negocio: "Daños",
    oficina_emision: "Sucursal 1, Mérida, Yucatán",
    id_oficina_emision: "0010",
    numero_poliza: "98765",
    nombre_contratante_asegurado: "Sara Fernández",
    nombre_beneficiario: "Sara Fernández",
    estado_vigencia_id: "1",
    estado_pago_id: "0",
    fecha_inicio_vigencia: "07/02/2023",
    fecha_fin_vigencia: "07/02/2024",
    fecha_emision: "08/02/2023",
    periodicidad_pago: "Semestral",
    info_vehiculo: {
      tipo: "N/A",
      marca: "N/A",
      modelo: "N/A",
      color: "N/A",
      placas: "N/A",
    },
    siniestros: [],
  },
  {
    linea_negocio: "Autos",
    oficina_emision: "Sucursal 1, Guadalajara, Jalisco",
    id_oficina_emision: "0002",
    numero_poliza: "99999",
    nombre_contratante_asegurado: "Rosa Martínez",
    nombre_beneficiario: "Rosa Martínez",
    estado_vigencia_id: "0",
    estado_pago_id: "0",
    fecha_inicio_vigencia: "22/09/2022",
    fecha_fin_vigencia: "22/09/2023",
    fecha_emision: "23/09/2022",
    periodicidad_pago: "Trimestral",
    info_vehiculo: {
      tipo: "Focus",
      marca: "Ford",
      modelo: "2023",
      color: "Blanco",
      placas: "XYZ-123-A",
    },
    siniestros: [],
  },
];

export const usuarios = [
  {
    nombre: "Heved",
    apellido_paterno: "Ríos",
    apellido_materno: "Delgado",
    username: "hevedrd",
    password: "RoWh4v5d=91c@",
    perfil: "Asesor",
  },
  {
    nombre: "Carlos",
    apellido_paterno: "Murillo",
    apellido_materno: "Ortiz",
    username: "carlosmo",
    password: "tpWh4v3d=81i$",
    perfil: "Asesor",
  },
  {
    nombre: "Esteban",
    apellido_paterno: "Castillo",
    apellido_materno: "López",
    username: "estebancl",
    password: "MnZh6y2d=96t%",
    perfil: "Supervisor",
  },
]
